#!/usr/bin/env bash
# Setup load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt update
sudo apt-get -y install haproxy=2.0.\*

echo "

frontend alx_frontend
				bind :80
        default_backend alx_backend_1

backend alx_backend_1
        balance roundrobin
        server web-01 18.234.129.112:80 check
        server web-02 35.174.184.68:80 check

" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
