#!/usr/bin/env bash
# This script runs nginx command.
pkill -f "apache|nginx"
chown nginx:nginx /etc/nginx/nginx.conf
chmod u+rw g+rw /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx nginx
